/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Amenities {
    wheelchairAccessible: boolean;
    wifi: boolean;
    airConditioning: boolean;
    usb: boolean;
    bicycle: boolean;
}
