/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "../index";
export interface Arrival {
    lineCode: string;
    routeCode: string;
    lineName: string;
    vehicleDoorNo: string;
    lastLocationTime: string;
    lastSpeed: number;
    lastLocation: ToplasApi.Coordinates;
    stopOrder: number;
    minutesUntilArrival: number;
    amenities: ToplasApi.Amenities;
}
