/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type DayType = "working_day" | "saturday" | "sunday";
export declare const DayType: {
    readonly WorkingDay: "working_day";
    readonly Saturday: "saturday";
    readonly Sunday: "sunday";
};
