"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DayType = void 0;
exports.DayType = {
    WorkingDay: "working_day",
    Saturday: "saturday",
    Sunday: "sunday",
};
