/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Direction = "outbound" | "inbound";
export declare const Direction: {
    readonly Outbound: "outbound";
    readonly Inbound: "inbound";
};
