/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "..";
export interface LineStop {
    stopName: string;
    stopCode: number;
    coordinates: ToplasApi.Coordinates;
    direction: string;
    lineCode: string;
    lineId: number;
    routeCode: string;
    routeOrder: number;
    routeDirection: ToplasApi.Direction;
}
