/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface LineOnStop {
    lineCode: string;
    lineId: number;
    routeCode: string;
    routeId: number;
    routeName: string;
}
