/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "..";
export interface LineInfo {
    lineCode: string;
    lineId: number;
    lineName: string;
    routes: ToplasApi.RouteInfo[];
}
