/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "../index";
export interface LiveBus {
    lineId: number;
    routeCode: string;
    vehicleDoorNo: string;
    lastLocationTime: string;
    lastLocation: ToplasApi.Coordinates;
    stopOrder: number;
    stopId: number;
    stopEnterTime?: string;
    stopExitTime?: string;
}
