/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "..";
export interface LiveBusIndividual {
    vehicleDoorNo: string;
    lastLocationTime: string;
    lastLocation: ToplasApi.Coordinates;
    vehiclePlate: string;
    speed: number;
}
