/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "../index";
export interface TimetableTrip {
    lineCode: string;
    routeCode: string;
    time: string;
    dayType: ToplasApi.DayType;
    direction: ToplasApi.Direction;
}
