/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ToplasApi from "../index";
export interface ValidationError {
    loc: ToplasApi.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
