/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface VehicleTask {
    lineCode: string;
    routeCode?: string;
    lineName: string;
    taskStartTime: string;
}
