/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface VehicleInfo {
    operator: string;
    brandName: string;
    seatingCapacity: number;
    fullCapacity: number;
    year: number;
    vehicleType: string;
}
