/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { LineAnnouncement } from "../types/LineAnnouncement";
export declare const Response: core.serialization.Schema<serializers.lineAnnouncementsLiveLineLineCodeAnnouncementsGet.Response.Raw, ToplasApi.LineAnnouncement[]>;
export declare namespace Response {
    type Raw = LineAnnouncement.Raw[];
}
