/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const Response: core.serialization.Schema<serializers.lineAnnouncementsLiveLineLineCodeAnnouncementsGet.Response.Raw, ToplasApi.LineAnnouncement[]>;
export declare namespace Response {
    type Raw = serializers.LineAnnouncement.Raw[];
}
