/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { LineOnStop } from "../types/LineOnStop";
export declare const Response: core.serialization.Schema<serializers.linesOnStopStopStopCodeLinesGet.Response.Raw, ToplasApi.LineOnStop[]>;
export declare namespace Response {
    type Raw = LineOnStop.Raw[];
}
