/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { LiveBus } from "../types/LiveBus";
export declare const Response: core.serialization.Schema<serializers.liveBusesOnRoute.Response.Raw, ToplasApi.LiveBus[]>;
export declare namespace Response {
    type Raw = LiveBus.Raw[];
}
