/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { NearbyStop } from "../types/NearbyStop";
export declare const Response: core.serialization.Schema<serializers.nearbyStopsStopsGet.Response.Raw, ToplasApi.NearbyStop[]>;
export declare namespace Response {
    type Raw = NearbyStop.Raw[];
}
