/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { LineStop } from "../types/LineStop";
export declare const Response: core.serialization.Schema<serializers.routeStopsRouteRouteCodeStopsGet.Response.Raw, ToplasApi.LineStop[]>;
export declare namespace Response {
    type Raw = LineStop.Raw[];
}
