/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Route } from "../types/Route";
export declare const Response: core.serialization.Schema<serializers.routesLineLineCodeRoutesGet.Response.Raw, ToplasApi.Route[]>;
export declare namespace Response {
    type Raw = Route.Raw[];
}
