/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { TimetableTrip } from "../types/TimetableTrip";
export declare const Response: core.serialization.Schema<serializers.routeTimetableRouteRouteCodeTimetableGet.Response.Raw, ToplasApi.TimetableTrip[]>;
export declare namespace Response {
    type Raw = TimetableTrip.Raw[];
}
