/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Line } from "../types/Line";
export declare const Response: core.serialization.Schema<serializers.searchRoute.Response.Raw, ToplasApi.Line[]>;
export declare namespace Response {
    type Raw = Line.Raw[];
}
