/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Stop } from "../types/Stop";
export declare const Response: core.serialization.Schema<serializers.searchStop.Response.Raw, ToplasApi.Stop[]>;
export declare namespace Response {
    type Raw = Stop.Raw[];
}
