/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { StopAnnouncement } from "../types/StopAnnouncement";
export declare const Response: core.serialization.Schema<serializers.stopAnnouncementsLiveStopStopCodeAnnouncementsGet.Response.Raw, ToplasApi.StopAnnouncement[]>;
export declare namespace Response {
    type Raw = StopAnnouncement.Raw[];
}
