/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Arrival } from "../types/Arrival";
export declare const Response: core.serialization.Schema<serializers.stopArrivals.Response.Raw, ToplasApi.Arrival[]>;
export declare namespace Response {
    type Raw = Arrival.Raw[];
}
