/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as ToplasApi from "../index";
export declare class UnprocessableEntityError extends errors.ToplasApiError {
    constructor(body: ToplasApi.HttpValidationError);
}
