/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         lat: 1.1,
 *         lon: 1.1
 *     }
 */
export interface NearbyStopsStopsGetRequest {
    lat: number;
    lon: number;
    radius?: number;
}
