/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import * as ToplasApi from "./api";
export declare namespace ToplasApiClient {
    interface Options {
        environment?: core.Supplier<environments.ToplasApiEnvironment | string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class ToplasApiClient {
    protected readonly _options: ToplasApiClient.Options;
    constructor(_options?: ToplasApiClient.Options);
    readRootGet(requestOptions?: ToplasApiClient.RequestOptions): Promise<unknown>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.lineStopsLineLineCodeStopsGet("line_code", {})
     */
    lineStopsLineLineCodeStopsGet(lineCode: string, request?: ToplasApi.LineStopsLineLineCodeStopsGetRequest, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LineStop[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.routesLineLineCodeRoutesGet("line_code")
     */
    routesLineLineCodeRoutesGet(lineCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.Route[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.timetableLineLineCodeTimetableGet("line_code")
     */
    timetableLineLineCodeTimetableGet(lineCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.TimetableTrip[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.lineInfo("line_code")
     */
    lineInfo(lineCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LineInfo>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.routeStopsRouteRouteCodeStopsGet("route_code")
     */
    routeStopsRouteRouteCodeStopsGet(routeCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LineStop[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.routeTimetableRouteRouteCodeTimetableGet("route_code")
     */
    routeTimetableRouteRouteCodeTimetableGet(routeCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.TimetableTrip[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.routeInfo("route_code")
     */
    routeInfo(routeCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.RouteInfo>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.nearbyStopsStopsGet({
     *         lat: 1.1,
     *         lon: 1.1
     *     })
     */
    nearbyStopsStopsGet(request: ToplasApi.NearbyStopsStopsGetRequest, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.NearbyStop[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.linesOnStopStopStopCodeLinesGet("stop_code", {})
     */
    linesOnStopStopStopCodeLinesGet(stopCode: string, request?: ToplasApi.LinesOnStopStopStopCodeLinesGetRequest, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LineOnStop[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.stopInfo(1)
     */
    stopInfo(stopCode: number, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.StopInfo>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.liveBusesOnRoute("line_code")
     */
    liveBusesOnRoute(lineCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LiveBus[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.lineAnnouncementsLiveLineLineCodeAnnouncementsGet("line_code")
     */
    lineAnnouncementsLiveLineLineCodeAnnouncementsGet(lineCode: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LineAnnouncement[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.stopArrivals(1)
     */
    stopArrivals(stopCode: number, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.Arrival[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.stopAnnouncementsLiveStopStopCodeAnnouncementsGet(1)
     */
    stopAnnouncementsLiveStopStopCodeAnnouncementsGet(stopCode: number, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.StopAnnouncement[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.busLocationLiveBusVehicleDoorNoGet("vehicle_door_no")
     */
    busLocationLiveBusVehicleDoorNoGet(vehicleDoorNo: string, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.LiveBusIndividual>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.searchRoute({
     *         query: "query"
     *     })
     */
    searchRoute(request: ToplasApi.SearchRouteRequest, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.Line[]>;
    /**
     * @throws {@link ToplasApi.UnprocessableEntityError}
     *
     * @example
     *     await toplasApi.searchStop({
     *         query: "query"
     *     })
     */
    searchStop(request: ToplasApi.SearchStopRequest, requestOptions?: ToplasApiClient.RequestOptions): Promise<ToplasApi.Stop[]>;
}
