/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const ToplasApiEnvironment: {
    readonly Default: "/api";
};
export declare type ToplasApiEnvironment = typeof ToplasApiEnvironment.Default;
