"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToplasApiEnvironment = void 0;
exports.ToplasApiEnvironment = {
    Default: "/api",
};
