"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Arrival = void 0;
const core = __importStar(require("../../core"));
const Coordinates_1 = require("./Coordinates");
const Amenities_1 = require("./Amenities");
exports.Arrival = core.serialization.object({
    lineCode: core.serialization.property("line_code", core.serialization.string()),
    routeCode: core.serialization.property("route_code", core.serialization.string()),
    lineName: core.serialization.property("line_name", core.serialization.string()),
    vehicleDoorNo: core.serialization.property("vehicle_door_no", core.serialization.string()),
    lastLocationTime: core.serialization.property("last_location_time", core.serialization.string()),
    lastSpeed: core.serialization.property("last_speed", core.serialization.number()),
    lastLocation: core.serialization.property("last_location", Coordinates_1.Coordinates),
    stopOrder: core.serialization.property("stop_order", core.serialization.number()),
    minutesUntilArrival: core.serialization.property("minutes_until_arrival", core.serialization.number()),
    amenities: Amenities_1.Amenities,
});
