/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const Arrival: core.serialization.ObjectSchema<serializers.Arrival.Raw, ToplasApi.Arrival>;
export declare namespace Arrival {
    interface Raw {
        line_code: string;
        route_code: string;
        line_name: string;
        vehicle_door_no: string;
        last_location_time: string;
        last_speed: number;
        last_location: serializers.Coordinates.Raw;
        stop_order: number;
        minutes_until_arrival: number;
        amenities: serializers.Amenities.Raw;
    }
}
