/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
export declare const DayType: core.serialization.Schema<serializers.DayType.Raw, ToplasApi.DayType>;
export declare namespace DayType {
    type Raw = "working_day" | "saturday" | "sunday";
}
