/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const Direction: core.serialization.Schema<serializers.Direction.Raw, ToplasApi.Direction>;
export declare namespace Direction {
    type Raw = "outbound" | "inbound";
}
