/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const LineInfo: core.serialization.ObjectSchema<serializers.LineInfo.Raw, ToplasApi.LineInfo>;
export declare namespace LineInfo {
    interface Raw {
        line_code: string;
        line_id: number;
        line_name: string;
        routes: serializers.RouteInfo.Raw[];
    }
}
