/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const LineStop: core.serialization.ObjectSchema<serializers.LineStop.Raw, ToplasApi.LineStop>;
export declare namespace LineStop {
    interface Raw {
        stop_name: string;
        stop_code: number;
        coordinates: serializers.Coordinates.Raw;
        direction: string;
        line_code: string;
        line_id: number;
        route_code: string;
        route_order: number;
        route_direction: serializers.Direction.Raw;
    }
}
