/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
export declare const LineOnStop: core.serialization.ObjectSchema<serializers.LineOnStop.Raw, ToplasApi.LineOnStop>;
export declare namespace LineOnStop {
    interface Raw {
        line_code: string;
        line_id: number;
        route_code: string;
        route_id: number;
        route_name: string;
    }
}
