/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Coordinates } from "./Coordinates";
import { Amenities } from "./Amenities";
import { VehicleInfo } from "./VehicleInfo";
export declare const LiveBusIndividual: core.serialization.ObjectSchema<serializers.LiveBusIndividual.Raw, ToplasApi.LiveBusIndividual>;
export declare namespace LiveBusIndividual {
    interface Raw {
        vehicle_door_no: string;
        last_location_time: string;
        last_location: Coordinates.Raw;
        vehicle_plate: string;
        speed: number;
        amenities: Amenities.Raw;
        vehicle_info: VehicleInfo.Raw;
    }
}
