/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Coordinates } from "./Coordinates";
export declare const NearbyStop: core.serialization.ObjectSchema<serializers.NearbyStop.Raw, ToplasApi.NearbyStop>;
export declare namespace NearbyStop {
    interface Raw {
        stop_name: string;
        stop_code: number;
        stop_id: number;
        coordinates: Coordinates.Raw;
        direction: string;
        distance: number;
    }
}
