/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const Route: core.serialization.ObjectSchema<serializers.Route.Raw, ToplasApi.Route>;
export declare namespace Route {
    interface Raw {
        line_code: string;
        line_id: number;
        line_description?: string | null;
        line_name: string;
        route_code: string;
        route_id: number;
        route_description?: string | null;
        route_name: string;
        route_direction: serializers.Direction.Raw;
    }
}
