/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Direction } from "./Direction";
import { LineStop } from "./LineStop";
import { TimetableTrip } from "./TimetableTrip";
export declare const RouteInfo: core.serialization.ObjectSchema<serializers.RouteInfo.Raw, ToplasApi.RouteInfo>;
export declare namespace RouteInfo {
    interface Raw {
        line_code: string;
        line_id: number;
        line_description?: string | null;
        line_name: string;
        route_code: string;
        route_id: number;
        route_description?: string | null;
        route_name: string;
        route_direction: Direction.Raw;
        stops: LineStop.Raw[];
        trips: TimetableTrip.Raw[];
    }
}
