/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const RouteInfo: core.serialization.ObjectSchema<serializers.RouteInfo.Raw, ToplasApi.RouteInfo>;
export declare namespace RouteInfo {
    interface Raw {
        line_code: string;
        line_id: number;
        line_description?: string | null;
        line_name: string;
        route_code: string;
        route_id: number;
        route_description?: string | null;
        route_name: string;
        route_direction: serializers.Direction.Raw;
        stops: serializers.LineStop.Raw[];
        trips: serializers.TimetableTrip.Raw[];
    }
}
