/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const Stop: core.serialization.ObjectSchema<serializers.Stop.Raw, ToplasApi.Stop>;
export declare namespace Stop {
    interface Raw {
        stop_name: string;
        stop_code: number;
        stop_id: number;
        coordinates: serializers.Coordinates.Raw;
        direction: string;
    }
}
