/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const StopInfo: core.serialization.ObjectSchema<serializers.StopInfo.Raw, ToplasApi.StopInfo>;
export declare namespace StopInfo {
    interface Raw {
        stop_name: string;
        stop_code: number;
        stop_id: number;
        coordinates: serializers.Coordinates.Raw;
        direction: string;
        lines: serializers.LineOnStop.Raw[];
    }
}
