/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { Coordinates } from "./Coordinates";
import { LineOnStop } from "./LineOnStop";
export declare const StopInfo: core.serialization.ObjectSchema<serializers.StopInfo.Raw, ToplasApi.StopInfo>;
export declare namespace StopInfo {
    interface Raw {
        stop_name: string;
        stop_code: number;
        stop_id: number;
        coordinates: Coordinates.Raw;
        direction: string;
        lines: LineOnStop.Raw[];
    }
}
