/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
import { DayType } from "./DayType";
import { Direction } from "./Direction";
export declare const TimetableTrip: core.serialization.ObjectSchema<serializers.TimetableTrip.Raw, ToplasApi.TimetableTrip>;
export declare namespace TimetableTrip {
    interface Raw {
        line_code: string;
        route_code: string;
        time: string;
        day_type: DayType.Raw;
        direction: Direction.Raw;
    }
}
