/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as ToplasApi from "../../api";
import * as core from "../../core";
export declare const TimetableTrip: core.serialization.ObjectSchema<serializers.TimetableTrip.Raw, ToplasApi.TimetableTrip>;
export declare namespace TimetableTrip {
    interface Raw {
        line_code: string;
        route_code: string;
        time: string;
        day_type: serializers.DayType.Raw;
        direction: serializers.Direction.Raw;
    }
}
