/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
export declare const VehicleTask: core.serialization.ObjectSchema<serializers.VehicleTask.Raw, ToplasApi.VehicleTask>;
export declare namespace VehicleTask {
    interface Raw {
        line_code: string;
        route_code?: string | null;
        line_name: string;
        task_start_time: string;
    }
}
