/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ToplasApi from "../../api/index";
import * as core from "../../core";
export declare const VehicleInfo: core.serialization.ObjectSchema<serializers.VehicleInfo.Raw, ToplasApi.VehicleInfo>;
export declare namespace VehicleInfo {
    interface Raw {
        operator: string;
        brand_name: string;
        seating_capacity: number;
        full_capacity: number;
        year: number;
        vehicle_type: string;
    }
}
